Bug Fixes
storm345dev/ucars pull request #8
Opened 2020-11-08 17:32 UTC by Jakllp

I noticed some bugs so I set out to fix them. This is what I did:

Letting roller coasters roll again
Storagecarts etc drop correctly now
Better configs (e.g. black_wool instead of WOOL:15 as roadblocks)

2020-11-08 17:46 UTC, closed without merging

2020-11-08 18:04 UTC, storm345 requested changes
Had a look through and made some comments that will need addressing before it can be merged.

Looks like a bunch of this is updating for 1.16 whereas the master branch of uCars is for 1.12 currently. Ideally if the change can support both would be ideal, or if not then it ought to be a different branch for 1.16. 

There also seem to be a few small potential bugs - such as assuming the car is a Minecart and ignoring a custom hitbox for collisions.

It also would be a lot better to support or convert existing configurations and their definitions of material:data for types.

2020-11-08 18:04 UTC, storm345 commented on src/main/java/com/useful/ucars/ucars.java
> +	public final Boolean isBlockEqualToConfigIds(List<String> rawIds, String blockName) {
Ought to support or convert existing config values. Perhaps prefer to convert to standard bukkit itemstack config representation

2020-11-08 18:04 UTC, storm345 commented on src/main/resources/plugin.yml
> +api-version: 1.16
The master branch of uCars should be 1.12 compatible as the primary version for now. 1.16 can be a separate branch, or can also be supported in addition to 1.12 but 1.12 must be compatible.

2020-11-09 00:15 UTC, Jakllp commented on src/main/java/com/useful/ucars/uCarsListener.java
> +			checks.add("RAIL");
I assume you mean MC-VERSIONS?